'use strict';
const fs=require('fs');const path=require('path');const {spawnSync,execFileSync}=require('child_process');
const ROOT=path.resolve(__dirname,'..');const COPILOT=path.join(ROOT,'work','GitHub CLI','copilot','copilot.exe');const GH=path.join(ROOT,'work','gh','bin','gh.exe');const LLM=path.join(ROOT,'data','processed','llm-comparison');const SECOND=path.join(ROOT,'data','processed','second-review');fs.mkdirSync(LLM,{recursive:true});fs.mkdirSync(SECOND,{recursive:true});
const baseEnv={...process.env,GH_CONFIG_DIR:path.join(ROOT,'work','gh-config'),COPILOT_HOME:path.join(ROOT,'work','copilot-home'),LOCALAPPDATA:path.join(ROOT,'work'),HTTPS_PROXY:'http://127.0.0.1:7897',HTTP_PROXY:'http://127.0.0.1:7897'};baseEnv.COPILOT_GITHUB_TOKEN=execFileSync(GH,['auth','token'],{env:baseEnv,encoding:'utf8'}).trim();
const system=`你是游戏反馈分析标注员。对每条评论输出 JSON 数组，字段仅包含 feedback_id、theme、sentiment、severity。\n主题：性能与优化、外挂与安全、匹配与队友、武器与干员平衡、搜打撤与经济、地图与模式、付费与通行证、任务与成长、客服与封禁、界面与操作体验、正向反馈、其他。\n情绪：正向、负向、混合、中性。严重度：低、中、高、严重。\n优先考虑阻断游玩、账号安全和信任问题。不要调用工具，不要读取文件，只输出 JSON。`;
function parseJson(text){const clean=text.replace(/\x1b\[[0-9;]*m/g,'');const a=clean.indexOf('['),b=clean.lastIndexOf(']');if(a<0||b<a)throw new Error('未找到 JSON：'+clean.slice(0,300));return JSON.parse(clean.slice(a,b+1));}
function classify(items){const out=[];for(let i=0;i<items.length;i+=10){const chunk=items.slice(i,i+10);const prompt=system+'\n\n输入：'+JSON.stringify(chunk.map(x=>({feedback_id:x.feedback_id,content:x.content,rating:x.rating||''})));console.log('分类 '+i+'-'+Math.min(i+9,items.length-1));const r=spawnSync(COPILOT,['-p',prompt,'--allow-all-tools','--no-color'],{env:baseEnv,encoding:'utf8',maxBuffer:10*1024*1024,timeout:180000});if(r.status!==0)throw new Error('Copilot 失败：'+(r.stderr||r.stdout));out.push(...parseJson(r.stdout));}return out;}
function metrics(rows,key){const valid=rows.filter(x=>x.human&&x.human[key]&&x.ai&&x.ai[key]);const ok=valid.filter(x=>x.human[key]===x.ai[key]).length;return{field:key,accuracy:Number((ok/(valid.length||1)*100).toFixed(1)),correct:ok,total:valid.length};}
(async()=>{const sample=JSON.parse(fs.readFileSync(path.join(LLM,'sample.json'),'utf8'));const prev=fs.existsSync(path.join(LLM,'copilot-predictions.json'))?JSON.parse(fs.readFileSync(path.join(LLM,'copilot-predictions.json'),'utf8')):[];const pred=prev.length===sample.length?prev:classify(sample);fs.writeFileSync(path.join(LLM,'copilot-predictions.json'),JSON.stringify(pred,null,2),'utf8');const map={};pred.forEach(x=>map[x.feedback_id]=x);const compared=sample.map(x=>({...x,ai:map[x.feedback_id]||null}));fs.writeFileSync(path.join(LLM,'comparison.json'),JSON.stringify(compared,null,2),'utf8');const results={status:'completed',model:'GitHub Copilot CLI',generated_at:new Date().toISOString(),sample_size:sample.length,metrics:[metrics(compared,'theme'),metrics(compared,'sentiment'),metrics(compared,'severity')],note:'人工抽检样本曾用于规则校准；这里比较的是人工标签与 Copilot 独立分类，不代表独立测试集。'};fs.writeFileSync(path.join(LLM,'results.json'),JSON.stringify(results,null,2),'utf8');
const csv=fs.readFileSync(path.join(SECOND,'second-reviewer-template.csv'),'utf8');const lines=csv.replace(/^\ufeff/,'').split(/\r?\n/).filter(Boolean);const header=lines.shift().split(',');const rows=lines.map(line=>{const cells=[];let cur='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(c===','&&!q){cells.push(cur);cur=''}else cur+=c}cells.push(cur);const o={};header.forEach((h,i)=>o[h]=cells[i]||'');return o;});const secondPred=classify(rows);const pmap={};secondPred.forEach(x=>pmap[x.feedback_id]=x);const secondOut=rows.map(r=>({...r,...(pmap[r.feedback_id]||{}),ai_theme:(pmap[r.feedback_id]||{}).theme||'',ai_sentiment:(pmap[r.feedback_id]||{}).sentiment||'',ai_severity:(pmap[r.feedback_id]||{}).severity||''}));fs.writeFileSync(path.join(SECOND,'second-reviewer-ai.json'),JSON.stringify(secondOut,null,2),'utf8');function esc(v){const s=String(v==null?'':v);return /[",\r\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s;}const cols=['feedback_id','source','published_at','content','rating','ai_theme','ai_sentiment','ai_severity','reviewer_notes'];fs.writeFileSync(path.join(SECOND,'second-reviewer-ai-completed.csv'),'\ufeff'+[cols.join(',')].concat(secondOut.map(r=>cols.map(c=>esc(r[c])).join(','))).join('\r\n'),'utf8');console.log(JSON.stringify(results,null,2));console.log('独立 AI 复核完成：'+secondOut.length+' 条');})().catch(e=>{console.error(e.stack||e.message);process.exit(1);});
