'use strict';
const fs=require('fs');const path=require('path');const https=require('https');
const ROOT=path.resolve(__dirname,'..');const OUT=path.join(ROOT,'data','processed','llm-comparison');const PROMPTS=path.join(ROOT,'prompts');fs.mkdirSync(OUT,{recursive:true});fs.mkdirSync(PROMPTS,{recursive:true});
const rows=JSON.parse(fs.readFileSync(path.join(ROOT,'data','processed','analysis.json'),'utf8')).filter(r=>r.human_theme);
const sample=rows.map(r=>({feedback_id:r.feedback_id,source:r.source,content:r.content,rating:r.rating,human:{theme:r.human_theme,sentiment:r.human_sentiment,severity:r.human_severity},rules:{theme:r.theme,sentiment:r.sentiment,severity:r.severity}}));
fs.writeFileSync(path.join(OUT,'sample.json'),JSON.stringify(sample,null,2),'utf8');
const prompt=`你是游戏用户反馈分析标注员。请对输入评论逐条输出 JSON 数组，每条必须包含：feedback_id、theme、sentiment、severity。\n主题只能是：性能与优化、外挂与安全、匹配与队友、武器与干员平衡、搜打撤与经济、地图与模式、付费与通行证、任务与成长、客服与封禁、界面与操作体验、正向反馈、其他。\n情绪只能是：正向、负向、混合、中性。\n严重度只能是：低、中、高、严重。\n规则：优先判断影响账号安全和无法正常游玩的问题；同时有优点和问题时情绪可为混合；语义不足时主题为其他、情绪为中性、严重度为低。只输出 JSON，不输出解释。`;
fs.writeFileSync(path.join(PROMPTS,'feedback-classification-prompt.md'),prompt,'utf8');
function requestJson(url,key,model,payload){return new Promise((resolve,reject)=>{const data=JSON.stringify(payload);const u=new URL(url);const req=https.request({hostname:u.hostname,path:u.pathname+u.search,method:'POST',headers:{'content-type':'application/json','authorization':'Bearer '+key,'content-length':Buffer.byteLength(data)}},r=>{let body='';r.on('data',c=>body+=c);r.on('end',()=>{if(r.statusCode<200||r.statusCode>=300)reject(new Error('HTTP '+r.statusCode+' '+body.slice(0,300)));else resolve(JSON.parse(body));});});req.on('error',reject);req.write(data);req.end();});}
function metric(key,label){const ok=sample.filter(x=>x.rules[key]===x.human[key]).length;return {field:label,accuracy:Number((ok/sample.length*100).toFixed(1)),correct:ok,total:sample.length};}
(async()=>{const key=process.env.LLM_API_KEY||process.env.OPENAI_API_KEY;const model=process.env.LLM_MODEL||process.env.OPENAI_MODEL;const base=process.env.LLM_API_URL||'https://api.openai.com/v1/chat/completions';if(!key||!model){const status={status:'pending_external_credentials',reason:'缺少 LLM_API_KEY/OPENAI_API_KEY 或 LLM_MODEL/OPENAI_MODEL。',sample_size:sample.length,model:model||null,api_url:base,generated_at:new Date().toISOString(),next:'配置环境变量后重新运行 node src/llm_compare.js'};fs.writeFileSync(path.join(OUT,'status.json'),JSON.stringify(status,null,2),'utf8');console.log(JSON.stringify(status,null,2));return;}const payload={model,messages:[{role:'system',content:prompt},{role:'user',content:JSON.stringify(sample.map(x=>({feedback_id:x.feedback_id,content:x.content,rating:x.rating})))}],response_format:{type:'json_object'}};const res=await requestJson(base,key,model,payload);const text=res.choices&&res.choices[0]&&res.choices[0].message&&res.choices[0].message.content;const parsed=JSON.parse(text);const list=Array.isArray(parsed)?parsed:(parsed.items||parsed.results||[]);fs.writeFileSync(path.join(OUT,'llm-predictions.json'),JSON.stringify(list,null,2),'utf8');const map={};list.forEach(x=>map[x.feedback_id]=x);const compared=sample.map(x=>({...x,llm:map[x.feedback_id]||null}));fs.writeFileSync(path.join(OUT,'comparison.json'),JSON.stringify(compared,null,2),'utf8');const results={status:'completed',model,generated_at:new Date().toISOString(),metrics:[metric('theme','主题'),metric('sentiment','情绪'),metric('severity','严重度')],note:'规则分类与人工抽检样本曾用于规则校准，因此这不是独立测试集。'};fs.writeFileSync(path.join(OUT,'results.json'),JSON.stringify(results,null,2),'utf8');console.log(JSON.stringify(results,null,2));})().catch(e=>{console.error(e.stack||e.message);process.exit(1);});
